prod:
  children:

    # k3s nodes running the control plane
    k3s_managers:
      hosts:
        192.168.30.105:
        192.168.30.106:
        192.168.30.107:

    # k3s nodes that don't run the control plane
    k3s_workers:
      hosts:

    # k3s represents the entire k3s cluster
    k3s:
      children:
        k3s_managers:
        k3s_workers: