---
- name: install rng-tools
  package:
    name: rng-tools
    state: present
  become: yes

- name: start & enable rng-tools service
  service:
    name: rng-tools
    state: started
    enabled: yes