---
- name: update apt cache
  raw: apt-get update
  ignore_errors: yes
  become: yes

- name: install python
  raw: apt-get -yqq install python3 python3-pip
  ignore_errors: yes
  become: yes

- name: install wheel,setuptools, and openshift
  raw: pip3 install wheel setuptools openshift
  ignore_errors: no
  become: yes