---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Python
  apt:
    pkg: 
    - python3
    - python3-pip
  become: yes

- name: Pip Install wheel, setuptools, and openshift
  pip: 
    name: 
    - setuptools
    - wheel
    - openshift
  become: yes 
